### DISCUSSION TITLE
Is async backing supported?

### DISCUSSION THREAD

**Discussion by timbrinded** [paritytech/zombienet#1714] [Q&A] [answered]
How do you configure relay chain to use async backing?

**Comment by pepoviola** [comment, marked as answer]
Hey @timbrinded, yes is supported. For example, using rococo-local as chain you can set this changes in the genesis config (in your `toml`).

```toml
[relaychain.genesis.runtimeGenesis.patch.configuration.config]
scheduling_lookahead = 2

[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
max_candidate_depth = 3
allowed_ancestry_len = 2
```
Thx!
