### ISSUE TITLE
KAGOME does not launch with correct ws-port

### ISSUE THREAD

**Issue by kamilsa** [paritytech/zombienet#1037]
### Issue Description

KAGOME used to work okay with zombienet version 1.3.44 and lower. However, when #984 was introduced we started to observe that KAGOME is starting with default ws-port (9944) instead of the one that zombienet prints when network is launched (in Network launched 🚀🚀 section)

### Steps to reproduce the issue

Steps to reproduce the issue
1. Download ([link](https://drive.google.com/file/d/1KHiy0PXVRnhe6WKsvjxDbSju957AFqbx/view?usp=share_link) for macos) or [build](https://github.com/soramitsu/kagome#build) KAGOME binary
2. Ensure kagome and polkadot binaries are added to the path
3. Download sample [config_2.toml](https://gist.github.com/kamilsa/8d5f75befe4c36e333fcedb7baa4d50a) for a test
4. run `./zombienet-macos spawn --provider native config_2.toml`

### Describe the results you received

We see that KAGOME is executed with the following command:
```
kagome --offchain-worker
      Never --chain
      /var/folders/68/9b5mh499731fysstdj0_j6cm0000gn/T/zombie-9e8fbf7128dcea3404c5613fa6a4cdb0_-95416-uoqBEPAyNYUR/b-0/cfg/polkadot-local.json
      --name b-0 --rpc-cors all --unsafe-rpc-external --rpc-methods unsafe
      --no-mdns --node-key
      c94d3162fbdd6773c490e50afd813c9eae06644fdd158c89c03a34ba5f7aacea
      --no-telemetry --prometheus-external --validator --bootnodes
      /ip4/127.0.0.1/tcp/54602/ws/p2p/12D3KooWFiYfdwonvypzeZJBz7dNKESHMG7kvUeexPGDVYnWRYLs
      --prometheus-port 54617 --rpc-port 54615 --listen-addr
      /ip4/0.0.0.0/tcp/54614/ws --base-path
      /var/folders/68/9b5mh499731fysstdj0_j6cm0000gn/T/zombie-9e8fbf7128dcea3404c5613fa6a4cdb0_-95416-uoqBEPAyNYUR/b-0/data
```

Note that there is no `--ws-port <port>` flag. However we see that it prints in `Network launched 🚀🚀` section:
```
Direct Link                  │ https://polkadot.js.org/apps/?rpc=ws://127.0.0.1:54615#/explorer
```
This link leads to nowhere

### Describe the results you expected

It is expected that zombienet would add `--ws-port <port>` flag for KAGOME binary and proper ws port number will be used in polkadot.js link

### Zombienet version

1.3.50

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 0.9.39-bf2ebf30780
kagome latest
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by kamilsa** [comment]
It is okay to assume that KAGOME will have `--ws-port` flag as long as it is printed in `--help` menu

**Comment by pepoviola** [comment]
Hi @kamilsa, I will try to reproduce since if the help show the `--ws-port` then we should use it for spawning the nodes.
Thanks!

**Comment by kamilsa** [comment]
@pepoviola thanks! FYI, in this PR, we will remove ws-port flag as it is done in substrate https://github.com/soramitsu/kagome/pull/1614

**Comment by pepoviola** [comment]
> @pepoviola thanks! FYI, in this PR, we will remove ws-port flag as it is done in substrate [soramitsu/kagome#1614](https://github.com/soramitsu/kagome/pull/1614)

Great, thanks for the info. I have review this case in my todo list. Let me know if works after remove the `ws-port` flag.

Thanks!

**Comment by pepoviola** [comment]
Hi @kamilsa, sorry about the delay. I review your config file.

```toml
[relaychain]
default_command = "polkadot"

chain = "polkadot-local"

  [[relaychain.node_groups]]
  name = "a"
  count = 3

  [[relaychain.node_groups]]
  name = "b"
  count = 1
  command = "kagome --offchain-worker Never"
  prometheus_prefix = "kagome"
```

And the issue is in the command definition `  command = "kagome --offchain-worker Never"`. Because zombienet use the command to check which version of substrate args are available (running `cmd --help`).

This config should work as expected

```toml
[relaychain]
default_command = "polkadot"

chain = "polkadot-local"

  [[relaychain.node_groups]]
  name = "a"
  count = 3

  [[relaychain.node_groups]]
  name = "b"
  count = 1
  command = "kagome"
  args = ["--offchain-worker", "Never"]
  prometheus_prefix = "kagome"
```

Closing here, please re-open if needed.
Thanks!!
