### ISSUE TITLE
Zombienet running with docker image 

### ISSUE THREAD

**Issue by felixfaisal** [paritytech/zombienet#1039]
### Issue Description

I would like to run a docker image which already has an entry point and just provide the args, how can I do this? 

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a docker image with entrypoint "target/release/collator" 
2. Include the  `image` in `config.toml`
3. Spawn the network 

### Describe the results you received

It does not work with an entry point already in the image

### Describe the results you expected

I should be able to define the config like this 
```toml
 34 [[parachains]]
 35 id = 1001
 36 # cumulus_based = true
 37 chain = "dev"
 38
 39 [parachains.collator]
 40 name = "parachain-B-1001-collator01"
 41 image = "parachain/parachain:latest"
 42 ws_port = 9902
```

### Zombienet version

latest

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 0.9.40-a2b62fb872b
polkadot-parachain 0.9.380-fe24f39507f
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Is it possible to do this with zombienet?

**Comment by pepoviola** [comment]
Hi @felixfaisal, you need to add the command to the config

```toml
[parachains.collator]
 name = "parachain-B-1001-collator01"
 image = "parachain/parachain:latest"
 command = "target/release/collator"
 ws_port = 9902
 ```
 
Can you please with this change?

Thanks!
