### ISSUE TITLE
New "minus" test is not working

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#1079]
### Issue Description

block height minus finalized is not working

### Steps to reproduce the issue

Use the toml:
```toml
# test.toml
[settings]
timeout = 1000

[relaychain]
chain = "westend-local"
command = "./bin/polkadot-fast-runtime"

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice" ]

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob" ]
```

zndsl file:
```yaml
Description: Smoke Test
Network: ./test.toml
Creds: config

alice: reports block height is at least 10 within 200 seconds
alice: reports block height minus finalised block is at least 10 within 200 seconds
```

and test that `block height` - `finalised block`  are printed and subscribed correctly

### Describe the results you received

2nd test passes

### Describe the results you expected

2nd test should fail

### Zombienet version

1.3.53

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 0.9.40-a2b62fb872b
polkadot-parachain 0.9.380-fe24f39507f
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
