### ISSUE TITLE
[k8s] Ability to test against bad network conditions

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#1092]
# The Vision

Zombienet clusters and internal testnets are usually spawned within a single data center, where network speeds are often close to optimal. Unfortunately, in the real world things are not so ideal. Therefore, I'd propose to extend zombienet functionality w/ ability to simulate bad & adversary network conditions.
(extracted from #903).

# The Plan

We want to first explore this scenarios using `k8s` (with [chaos-mesh](https://chaos-mesh.org/), since is already installed in our cluster) but we don't expose any way to configure the scenario for the test.

<details>
 <summary>Completed tasks</summary>
- [x] https://github.com/paritytech/zombienet/issues/927
- [x] https://github.com/paritytech/zombienet-sdk/issues/18
- [x] https://github.com/paritytech/zombienet-sdk/issues/17
</details>

[1302](https://github.com/paritytech/zombienet/issues/1302) Umbrella issue for tracking `Delay` tasks (latency/jitter) in both network config and test-runner.

[1336](https://github.com/paritytech/zombienet/issues/1336) Umbrella issue for partition/isolation in both network config / test-runner.

**Comment by pepoviola** [comment]
Hi @emamihe, is also possible to add latency to `pods` using those as selector right?
Thx!

**Comment by pepoviola** [comment]
> yes @pepoviola
> 
> ```
> delay:
>     latency: '100ms'
> ```
> 
> does this job

Just to clarify, we should apply a manifest with the `selector` for the pods. E.g.

```yml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay
spec:
  action: delay
  mode: all
  selector:
    pod:
      - hamid2
  delay:
    latency: '100ms'
    correlation: '100'
    jitter: '0ms'
```

Can you confirm please?
Thx!
