### ISSUE TITLE
[bug] dup bootnodes

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#126]
set `add_to_bootnodes = true` in both generate `dup` bootnodes for `bob`.

```toml
[relaychain]
default_image = "docker.io/paritypr/synth-wave:4131-0.9.12-ccd09bbf-29a1ac18"
chain = "rococo-local"
command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  extra_args = [ "--alice", "-lparachain=debug" ]
  add_to_bootnodes = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "--bob", "-lparachain=debug" ]
  add_to_bootnodes = true
```
