### ISSUE TITLE
[bug] wrong collator command

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#127]
without `args = ["-lparachain=debug"]` for `cumulus collators` the cmd generated is wrong.

```toml
[[parachains]]
id = 100
cumulus_based = true

  [parachains.collator]
  name = "collator1"
  image = "docker.io/paritypr/colander:4131-ccd09bbf"
  command = "polkadot-collator"
```
