### ISSUE TITLE
K8s provider: stuck in Launching transfer-files-container and timeout

### ISSUE THREAD

**Issue by doutv** [paritytech/zombienet#1324]
### Issue Description

Zombienet v1.3.66:
- Kubernetes provider stuck in Launching status and finally timeout.
- Native and Podman provider work fine. 

Zombienet v1.3.23:
**Kubernetes provider works fine**

### Steps to reproduce the issue

```sh
zombienet spawn test.toml
╔════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ 🧟 Zombienet 🧟    │ Initiation                                                                                         ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Provider           │ kubernetes                                                                                         ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Namespace          │ zombie-966a214bccf445882b611af1a5995683                                                            ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Temp Dir           │ /tmp/zombie-966a214bccf445882b611af1a5995683_-19415-fh1zgMffwcC2                                   ║
╚════════════════════╧════════════════════════════════════════════════════════════════════════════════════════════════════╝
┌─────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Pod                     │ temp                                                                                               │
├─────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Status                  │ Launching                                                                                          │
├─────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Image                   │ docker.io/parity/polkadot:latest                                                                   │
├─────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Command                 │ bash -c polkadot --help | grep ws-port || echo "V1"                                                │
└─────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
Error:           Error: Timeout(0) for: waitLog(): pod: temp, container: transfer-files-container, log: waiting for tar to finish
```

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### Zombienet version

1.3.66

### Provider

Kubernetes

### Provider version

```yaml
WSL2 Ubuntu 22.04

## kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3

## docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:45 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Upstream Latest Release

Yes

### Additional environment details

test.toml
```toml
[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  image = "docker.io/parity/polkadot:latest"
  validator = true
  args = ["--database=paritydb-experimental"]
```

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
