### ISSUE TITLE
[chaos-k8s] Add network config support for partition.

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#1337]
Example manifest

```yml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: partition
spec:
  action: partition
  mode: all
  selector:
    pods:
      zombie-xyzaskjdkjasdkajs:
      - Alice
  direction: to
  target:
    mode: all
    selector:
      pods:
        zombie-xyzaskjdkjasdkajs:
        - Bob
     ```
