### ISSUE TITLE
Cannot start a network with chainspec for parachain

### ISSUE THREAD

**Issue by weezy20** [paritytech/zombienet#1342]
### Issue Description

I am trying to start a network by passing a different `--chain` parameter and it seems zombienet won't let me : 

```toml
[[parachains]]
id = 2000
cumulus_based = true 
chain = "main"
```
This doesn't work, zombienet fails on the `build-spec` stage: 
```sh 
Tearing down network...

UnhandledRejection:      Error: Command failed with exit code 2: bash -c kill -9 
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```
If I remove the `chain = "main"` parameter, it works fine as usual. Just to eliminate any node related issues I pasted the same command that zombienet displays (before failing) while building the spec and it worked so it's probably a bug. 

Here's the full config: 
```toml
[settings]
timeout = 1000

[relaychain]
default_command = "./bin/polkadot-1"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true 
chain = "main"

  [parachains.collator]
  name = "007"
  command = "./target/release/parachain-template-node"
  args = [""] 
  ws_port = 9933
```

### Steps to reproduce the issue

Just run the above described config with `chain = *` in the parachain section.

### Describe the results you received

```sh

UnhandledRejection:      Error: Command failed with exit code 2: bash -c kill -9 
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

### Describe the results you expected

Successful boot of the network with the correct chain spec.

### Zombienet version

1.3.66

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 1.0
## Parachain
extended-parachain-template
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### Screenshots

![image](https://github.com/paritytech/zombienet/assets/15669111/1098587c-3aa4-4412-89f5-6af39f439080)
