### ISSUE TITLE
Crash with release-polkadot-v1.1.0

### ISSUE THREAD

**Issue by pgherveou** [paritytech/zombienet#1411]
### Issue Description

I am trying to run the relay chain with 2 validators this simple config 

```toml
[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9900
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "-lparachain=debug" ]
```

But the binary crash with 

```
at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466
  14: std::panic::catch_unwind::hf36acbaf210582be
      at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142
  15: std::rt::lang_start_internal::hadaf077a6dd0140b
      at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148
  16: _main<unknown>
      at <unknown source file>:<unknown line>
```

I built the `polkadot` binary from the release-polkadot-v1.1.0 branch 

### Steps to reproduce the issue

Steps to reproduce the issue
1. build polkadot cargo build --release  --bin polkadot
2. write config above to zombienet.toml
3. launch zombienet spawn --provider native zombienet.toml

### Describe the results you received

The relay chain crash as mentioned above

### Describe the results you expected

Not to crash :)

### Zombienet version

1.3.68

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 1.1.0-f60318f6868
```

### Upstream Latest Release

Yes

### Additional environment details

Macos Ventura M1

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
