### ISSUE TITLE
Zombienet usage in Jest-based e2e testing

### ISSUE THREAD

**Issue by ntn-x2** [paritytech/zombienet#1545]
### Is your feature request related to a problem? Please describe.

Hello,

we are developing an SDK for some cross-chain operations, and want to use Zombienet to spawn up different environments.

For the whole test environment to be fully reproducible, we are using the `"@zombienet/cli": "^1.3.82"` Node binary, and the following Zombienet config file:

```toml
[settings]
provider = "kubernetes"

[relaychain]
chain = "rococo-local"
default_image = "parity/polkadot:v1.0.0"
default_substrate_cli_args_version = 1

[[relaychain.nodes]]
name = "relay-alice"
rpc_port = 10001
ws_port = 10001

[[relaychain.nodes]]
name = "relay-bob"
rpc_port = 10002
ws_port = 10002

[[relaychain.nodes]]
name = "relay-charlie"
rpc_port = 10003
ws_port = 10003

[[parachains]]
id = 2000

[parachains.collator]
command = "node-executable"
name = "provider-alice"
image = "kiltprotocol/dip-provider-node-template:dev-release-bcc1f405a48563f9620930fde26519ee332e2ab4"
rpc_port = 10011
ws_port = 10011

[[parachains]]
id = 2001

[parachains.collator]
command = "node-executable"
name = "consumer-alice"
image = "kiltprotocol/dip-consumer-node-template:dev-release-bcc1f405a48563f9620930fde26519ee332e2ab4"
rpc_port = 10012
ws_port = 10012
```

The problems we are facing are the following:

* No matter what `ws_port` and `rpc_port` option we use, it does not seem to change the fact that a random port is chosen for relaychain and parachain nodes. This makes it very hard for any Node-based application to use the right port, if we don't know beforehand what port is used
* Given we want to 1. spin up a network, 2. run some tests against it, 3. teardown the network and the fact that the zombienet process does not really exit, we are force to spawn a second process which runs the tests, and then kill the original process, somehow. It would be best if the Zombienet script would offer an option to run in the background, providing some reference ID (e.g., the namespace) upon exiting, and then a different command, e.g., `zombienet teardown <namespace_id>` to teardown a previously created environment.

### Describe the solution you'd like

At the very least, a way to know beforehand the port numbers to be used by Zombienet. Additionally, a way to make it easier to run some processes after the Zombienet network has been set up.
