### ISSUE TITLE
Error fetching metrics

### ISSUE THREAD

**Issue by ntn-x2** [paritytech/zombienet#1578]
### Issue Description

Kubernetes-based setup with the following config:

```toml
[settings]
enable_tracing = false
provider = "kubernetes"

# Env variables:
# * RELAY_IMAGE: Docker image for relaychain nodes
# * RELAY_ALICE_RPC: RPC port for the `relay-alice` relaychain node
# * PROVIDER_IMAGE: Docker image for the DIP provider nodes
# * PROVIDER_ALICE_RPC: RPC port for the `provider-alice` provider node
# * CONSUMER_IMAGE: Docker image for the DIP consumer nodes
# * CONSUMER_ALICE_RPC: RPC port for the `consumer-alice` consumer node

[relaychain]
chain = "rococo-local"
default_image = "{{RELAY_IMAGE}}"
default_substrate_cli_args_version = 1

[[relaychain.nodes]]
name = "relay-alice"
rpc_port = "{{RELAY_ALICE_RPC}}"

[[relaychain.nodes]]
name = "relay-bob"

[[relaychain.nodes]]
name = "relay-charlie"

[[parachains]]
id = 2000

[parachains.collator]
command = "node-executable"
name = "provider-alice"
image = "{{PROVIDER_IMAGE}}"
rpc_port = "{{PROVIDER_ALICE_RPC}}"

[[parachains]]
id = 2001

[parachains.collator]
command = "node-executable"
name = "consumer-alice"
image = "{{CONSUMER_IMAGE}}"
rpc_port = "{{CONSUMER_ALICE_RPC}}"
```

Network spawn with the following command `yarn zombienet --spawn-concurrency 3 spawn tests/zombienet/network.toml`.

Relevant parts of GitHub CI configuration file:

```yaml
name: Lint and Test

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Install minikube
        uses: medyagh/setup-minikube@v0.0.14
      - name: Download source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Set environment variables
        run: cat ./tests/.env.test >> $GITHUB_ENV
      - name: Spin up network
        run: yarn test:e2e:start-network
```

Idea is to have the step to spin up the network run in the background with `&`, and have one more step listening for the ports: `until (nc -w 3 127.0.0.1 ${{ env.RELAY_ALICE_RPC }} && nc -w 3 127.0.0.1 ${{ env.PROVIDER_ALICE_RPC }} && nc -w 3 127.0.0.1 ${{ env.CONSUMER_ALICE_RPC }}) ; do sleep 1; done`.

The metrics problem stops the whole network from going up.

Additional details:
* `"@zombienet/cli": "^1.3.85"`
* `.nvmrc` -> `lts/Hydrogen` (Node 18)

![Screenshot 2023-12-04 at 12 28 01](https://github.com/paritytech/zombienet/assets/6704504/9566e69a-8d70-4991-982d-53cd6f09b39b)

### Steps to reproduce the issue

Metrics errors seems arbitrary when running locally, but it always reproduce when running on the CI environment. See above for more details.

### Describe the results you received

See above.

### Describe the results you expected

See above.

### Zombienet version

1.3.85

### Provider

Kubernetes

### Provider version

```yaml
See above.
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
