### ISSUE TITLE
More informative error when failing to decode type

### ISSUE THREAD

**Issue by mrcnski** [paritytech/zombienet#1599]
### Is your feature request related to a problem? Please describe.

It's possible to get an error like this:

```
         Error:  
                 createType(Header):: decodeU8aStruct: failed at 0xf10d89ba1e7bce… on extrinsicsRoot (index 4/5): H256:: Expected input with 32 bytes (256 bits), found 7 bytes
```

The fix is to add these lines, but it's not obvious:

```toml
[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
```

### Describe the solution you'd like

The error message could suggest how to fix the error, with a link to [`[Types]` doc](https://paritytech.github.io/zombienet/network-definition-spec.html#types) (and we can add an example to that doc).
