### ISSUE TITLE
Unable to start local cumulus collator

### ISSUE THREAD

**Issue by skunert** [paritytech/zombienet#161]
Hey, I was trying to start a minimal local network.

**Steps**
1. Cloned repo and build 
2. Modified https://github.com/paritytech/zombienet/blob/main/examples/0001-simple-network.toml and pointed the collator `command` field to `<cumulus_repo_path>/target/release/polkadot-collator`
3. Ran `node dist/cli.js -p native spawn examples/0001-simple-network.toml` as described in README

**Expected**
Network starts

**Error**
The collator is not coming up. The generated command is missing arguments, to me it looks like the collator is being treated the same as a relay chain node.

```
launching collator01
		 with command: /path/to/cumulus/target/release/polkadot-collator --chain /var/folders/d9/pq780q4x42j0krs6cp7bqcfm0000gn/T/zombie-b7d8ba4c77c842ac235aca07f1008d5f_-28461-AlOF9xXZ1uAV/collator01/cfg/rococo-local.json --name collator01 --rpc-cors all --unsafe-rpc-external --rpc-methods unsafe --unsafe-ws-external --no-mdns --node-key 5e123980fad4770d9ab5b7df7bbee8499943822a8555d11995e8203210065342 --no-telemetry --bootnodes /ip4/127.0.0.1/tcp/64497/ws/p2p/12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm --prometheus-port 64505 --rpc-port 64506 --ws-port 64507 --listen-addr /ip4/0.0.0.0/tcp/64508/ws --base-path /var/folders/d9/pq780q4x42j0krs6cp7bqcfm0000gn/T/zombie-b7d8ba4c77c842ac235aca07f1008d5f_-28461-AlOF9xXZ1uAV/collator01/data
Error: Timeout(30) for node : collator01
    at NativeClient.<anonymous> (/Users/skunert/work/repos/zombienet/dist/providers/native/nativeClient.js:267:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/skunert/work/repos/zombienet/dist/providers/native/nativeClient.js:5:58)
```

After looking quickly into the code it looks like an unexpected code path is taken here: https://github.com/paritytech/zombienet/blob/b2f940a98c928b295dcd5e91fdcea7230b2e42e6/src/providers/native/dynResourceDefinition.ts#L70 
`zombieRole` seems to be `collator` rather than `cumulus-collator`. 

Is this not supported yet or what are the required steps to get this to run?

**Comment by pepoviola** [comment]
Hi @skunert, 
                      Docs and examples are outdated, `cumulus` is supported but you need to declare in the network config the key  `cumulus_based` to true.

can you try this config?                      

```toml
[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  extra_args = [ "--alice", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "--bob", "-lparachain=debug" ]

[[parachains]]
id = 100
addToGenesis = false
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "{{COL_IMAGE}}"
  command = "/usr/local/bin/adder-collator"

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
```

Thanks!
