### ISSUE TITLE
Issue with overriding genesis state on polkadot 1.3.0 only

### ISSUE THREAD

**Issue by timbrinded** [paritytech/zombienet#1726]
### Issue Description

I've been trying to use the state override feature in the more recent versions of zombienet. What i'm finding however is that it is failing silently. Specifically, when trying to set async backing params of an old polkadot binary (1.3.0), zombienet halts and times out after finishing generating `temp-5.json`. 

It would be good to:
- Expose what the error is, as it currently times out
- Fix the underlying issue with why this is only a problem on 1.3.0 and not 1.6.0 (this may not be possible if the defect is in the polkadot bin itself)

### Steps to reproduce the issue

With the following toml:
```toml
[[parachains]]
cumulus_based = true
id = 2_001

[parachains.collator]
args = ["-lparachain=debug"]
command = "polkadot-parachain"
image = "parity/polkadot-parachain:1.3.0"
name = "collator02"

[relaychain]
chain = "rococo-local"
default_image = "docker.io/parity/polkadot:v1.3.0"

[relaychain.genesis.runtimeGenesis.patch.configuration.config]
scheduling_lookahead = 4

[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
allowed_ancestry_len = 4
max_candidate_depth = 4

[[relaychain.node_groups]]
args = ["-lparachain=debug"]
count = 2
name = "alice"

[settings]
timeout = 1_000

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
```
 
Run as normal, e.g. `./zombienet-linux-x64 -p kubernetes spawn configs/relaytest.toml`

### Describe the results you received

Starts as normal:
```sh
tmp/zombienet-linux-x64 -p kubernetes spawn configs/relaytest.toml
╔════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ 🧟 Zombienet 🧟    │ Initiation                                                                                         ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Provider           │ kubernetes                                                                                         ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Namespace          │ zombie-49e91ee12dff8684022dd220343709e5                                                            ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Temp Dir           │ /tmp/zombie-49e91ee12dff8684022dd220343709e5_-667028-83V0df20FF2o                                  ║
╚════════════════════╧════════════════════════════════════════════════════════════════════════════════════════════════════╝
┌─────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Pod                     │ temp                                                                                               │
├─────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Status                  │ Launching                                                                                          │
├─────────────────────────┼────────────────────────────────────────────────────────────────────
.....
```

However eventually times out:
```sh
└─────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Uploading:         │ /tmp/zombie-728e220cca5524b277279b15101b1f34_-563071-DllOOuppze8c/rococo-local-plain.json          │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ as:                │ 4a6b9f65cf3ce33531b679f1bf1a5269d80f0cbc3b8641bb039c35bde5c417b5                                   │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Pod                │ temp-5                                                                                             │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Status             │ Ready                                                                                              │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
Error:           Error: Timeout(0) for: waitLog(): pod: temp-5, container: temp-5, log: waiting for copy files to finish

undefined
┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Node'              │ /tmp/zombie-728e220cca5524b277279b15101b1f34_-563071-DllOOuppze8c/logs                             │
│ s logs:            │                                                                                                    │
│ m                  │                                                                                                    │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Zombie temp folder contains:
```sh
╰─λ tree .
.
├── 2001
│   ├── genesis-state
│   └── genesis-wasm
├── 2001-rococo-local.json
├── 2001-rococo-local-plain.json
├── finished.txt
├── logs
├── namespace
├── rococo-local-plain.json
├── temp-1.json
├── temp-2.json
├── temp-3.json
├── temp-4.json
├── temp-5.json
├── temp-collator.json
├── temp.json
└── zombie-wrapper.sh

3 directories, 15 files
```

### Describe the results you expected

Network to launch with state overrides applied to raw spec

### Zombienet version

1.3.92

### Provider

Kubernetes

### Provider version

```yaml
## For binaries
polkadot parity/polkadot:v1.3.0
polkadot-parachain parity/polkadot-parachain:1.3.0

kubectl version v1.29.1
cluster version v1.28.3
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by timbrinded** [comment]
Hi @pepoviola has anyone had the chance to look at this one yet? 

This issue is causing us some friction with enabling async backing on our testnets.

**Comment by pepoviola** [comment]
Hi @timbrinded, sorry about the delay. I will take a look today. Thanks for reporting!

**Comment by pepoviola** [comment]
Hi @timbrinded. I checked this issue and the problem is that in the `latest` version of zombienet we allow to `add` keys to the chain-spec genesis, so instead of fail to change these keys (since the spec of `v1.3.0` not have `runtimeGenesis.patch`):

```toml
[relaychain.genesis.runtimeGenesis.patch.configuration.config]
scheduling_lookahead = 4

[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
allowed_ancestry_len = 4
max_candidate_depth = 4
```
We are just adding those keys and showing a warning.

<img width="861" alt="image" src="https://github.com/paritytech/zombienet/assets/363911/697ebf94-4fce-4e0d-97fc-8a2824ed80f2">

And then the process of get the `raw` version fails:

<img width="633" alt="image" src="https://github.com/paritytech/zombienet/assets/363911/24e78165-b54f-481f-93d7-30a6b351b9b3">


---

For `1.3.0` you need to use the old structure of keys. This works as expected:

```toml
[relaychain.genesis.runtime.configuration.config]
scheduling_lookahead = 4


[relaychain.genesis.runtime.configuration.config.async_backing_params]
allowed_ancestry_len = 4
max_candidate_depth = 4
```

Let me know if does work, but I checked locally and I spawned the network without any issue.

Thanks again for your feedback and sorry about the delay!
