### ISSUE TITLE
Issue with transfers using js script

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#1773]
check https://substrate.stackexchange.com/questions/11328/zombienet-js-script-weird-behaviour

**Comment by pepoviola** [comment]
Hi @Szegoo, I  try to reproduce this issue but works as expected on my end. Can you check the version of zombienet with

```bash
 ./zombienet-macos version
1.3.100
```
And also the polkadot version, I used the v1.10.0 image 
```bash
POLKADOT_IMAGE=parity/polkadot:v1.10.0 ./zombienet-macos test support-files/1773.zndsl
```

<img width="1105" alt="image" src="https://github.com/paritytech/zombienet/assets/363911/3a09e138-b24f-40b0-bfb2-fd29211e324d">


Thanks!!

**Comment by Szegoo** [comment]
I did it from scratch as well, and it worked. It is possible (but unlikely) that I had the wrong Polkadot binaries. If I figure out what was causing the issue, I will post it here. Thanks!

**Comment by pepoviola** [comment]
> I did it from scratch as well, and it worked. It is possible (but unlikely) that I had the wrong Polkadot binaries. If I figure out what was causing the issue, I will post it here. Thanks!

Great, thanks! I think could be the case that the downloaded binaries were not the first option in the `PATH` and that why pick a wrong ones, but let me know if you see another issue.

Thanks!!

**Comment by Szegoo** [comment]
Ok, I think I discovered when the issue is occuring. Whenever I add the header types to the zombienet toml file I am getting the error. For example:

```toml
[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"

```
