### ISSUE TITLE
Can not work for AccountId20 network

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/zombienet#1826]
### Issue Description

Our session module's key should be `AccountId`. But it injects some `AccountId32` into it.

Auto generated:
```
"session": {
  "keys": [
    [
      "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
      "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
      {
        "grandpa": "5DaSuaLL4oLxWGR4c1GsvNgSaUuJWw5Pg7DRna5nU2TuNQhp",
        "babe": "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
        "im_online": "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
        "parachain_validator": "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
        "authority_discovery": "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
        "para_validator": "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
        "para_assignment": "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
        "beefy": "KW4wR5T7oX9fZgPyLsMaNyeLZ4HaC8b1iZtuDwQXNjEHYye1x",
        "aura": "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
        "nimbus": "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
        "vrf": "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
        "mixnet": "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
        "bcsv": "5DtWrR3CkMhwy5QEnmHqqMKBqSC7fcfnvT8jUykwFoh2seic",
        "ftsv": "5DaSuaLL4oLxWGR4c1GsvNgSaUuJWw5Pg7DRna5nU2TuNQhp"
      }
    ]
  ]
}
```

Expected:
```
"session": {
  "keys": [
    [
      "0x0eef9fabb6eb6fed2ab24a842931f8950426070a",
      "0x0eef9fabb6eb6fed2ab24a842931f8950426070a",
      {
        "aura": "5HTq3xdxVEG3CL68QYaUN72LJakLyRLDiGJXJEAJVxQ7m89c"
      }
    ],
    [
      "0xa858cde8f6cf178786578a3b0becf5c27d18300c",
      "0xa858cde8f6cf178786578a3b0becf5c27d18300c",
      {
        "aura": "5CyMRgKPspo6y357ErtbTz8ZbBkqQ26MXYxCMKZdHeXAWES3"
      }
    ],
    [
      "0x986b41d07776aa48f6d7a80caad49485f9a71714",
      "0x986b41d07776aa48f6d7a80caad49485f9a71714",
      {
        "aura": "5HBWTiQEtz86oPDwWjhTkxWjNDxW8RjZ1WPhWboK8rUWskJm"
      }
    ]
  ]
}
```

### Steps to reproduce the issue

```
gh repo clone darwinia-network/darwinia
cd darwinia
zombienet-macos-arm64 spawn .maintain/zombienet.toml
```

### Describe the results you received

```
Error:      Error: Command failed with exit code 1: bash -c tmp/darwinia build-spec --chain /var/folders/8h/_dnjtg3j5jz6bgp1bl5bqzbw0000gn/T/zombie-af881b4658db7afbdef7f5725f328918_-54307-wK8Xq5dmN0G7/koi-genesis-2105-rococo-local-plain.json --disable-default-bootnode  --raw > /var/folders/8h/_dnjtg3j5jz6bgp1bl5bqzbw0000gn/T/zombie-af881b4658db7afbdef7f5725f328918_-54307-wK8Xq5dmN0G7/koi-genesis-2105-rococo-local-raw.json
2024-06-26 17:23:47 Building chain spec    
Error: Service(Other("Invalid JSON blob: invalid length 48, expected a (both 0x-prefixed or not) hex string or byte array containing 20 bytes at line 1 column 3955"))
```

### Describe the results you expected

Run

### Zombienet version

Any

### Provider

Native

### Provider version

```yaml
## For binaries
Any
```

### Upstream Latest Release

Yes

**Comment by AurevoirXavier** [comment]
Is possible to not overwrite this file, and I can insert the keys manually through RPC.

**Comment by zianksm** [comment]
Yeah, im also having the same issues

**Comment by pepoviola** [comment]
Hi @AurevoirXavier / @zianksm, thanks for the feedback. I think this could be solved in https://github.com/paritytech/zombienet/pull/1816, since this introduce a new config key `force_decorator` (for parachain) and you can set the decorator to `generic-evm` (that use eth address for session).
Can you try and ping me if doesn't works as expected?
Thanks!!

**Comment by AurevoirXavier** [comment]
After adding `force_decorator = "generic-evm"` I got:

```
substrate/frame/session/src/lib.rs:481:52:
Validator in session 1 missing keys! 
```

Let me check if there's any wrong on my side.

**Comment by pepoviola** [comment]
Thanks for the feedback @AurevoirXavier, can you send me the network definition file (toml/json) to reproduce it on my end? 
Thanks!

**Comment by AurevoirXavier** [comment]
Is there a way to specify the session keys myself? We have our own staking(collator election) logic. Even this get fixed, the generated one wont work for us I think.

**Comment by AurevoirXavier** [comment]
> Thanks for the feedback @AurevoirXavier, can you send me the network definition file (toml/json) to reproduce it on my end? Thanks!

https://github.com/darwinia-network/darwinia/blob/main/.maintain/zombienet.toml

**Comment by pepoviola** [comment]
Hi @AurevoirXavier, sorry about the delay. I checked the `toml` and is defining multiple `parachains` block. Can you try with this network definition

```toml
[settings]
provider = "native"

[relaychain]
chain           = "rococo-local"
default_args    = ["--database=paritydb", "-lparachain=debug"]
default_command = "tmp/polkadot"

[[relaychain.nodes]]
name      = "alice"
validator = true
[[relaychain.nodes]]
name      = "bob"
validator = true

[[parachains]]
chain           = "koi-genesis"
force_decorator = "generic-evm"
id              = 2105
    [[parachains.collators]]
    args     = ["--database=paritydb", "--force-authoring", "-lparachain=debug"]
    command  = "tmp/darwinia"
    name     = "C1"
    rpc_port = 10000
    [[parachains.collators]]
    args     = ["--database=paritydb", "--force-authoring", "-lparachain=debug"]
    command  = "tmp/darwinia"
    name     = "C2"
    rpc_port = 10001
    [[parachains.collators]]
    args     = ["--database=paritydb", "--force-authoring", "-lparachain=debug"]
    command  = "tmp/darwinia"
    name     = "C3"
    rpc_port = 10002
```

Should works as expected, with 3 collators (and the keys in the session).

Thanks!! and again sorry about the delay.

**Comment by AlexD10S** [comment]
I encountered the same error using the [Zombienet-SDK](https://github.com/paritytech/zombienet-sdk). 
```
🚫 Could not launch local network: Orchestrator error: Provider error: File generation failed: 2024-08-16 17:09:39 Building chain spec    
Error: Service(Other("Invalid JSON blob: invalid length 48, expected a (both 0x-prefixed or not) hex string or byte array containing 20 bytes at line 1 column 1254"))
```
Does it require any additional configuration or specifications?

**Comment by pepoviola** [comment]
Hey @AlexD10S, does your parachain is evm based? Can you add this config to it

```toml
force_decorator = "generic-evm"
```

With this config should works in v1.

Thanks!

**Comment by ical10** [comment]
I'm also getting similar error:

```
2024-09-19 09:31:57 Building chain spec
Error: Service(Other("Invalid JSON blob: invalid length 48, expected a (both 0x-prefixed or not) hex string with length of 40 at line 38 column 56 for blob:...
```

Even with the `force_decorator` set to `"generic-evm"`.

Here is my config file:
```
[settings]
timeout = 1000
force_decorator = "generic-evm"

[relaychain]
default_command = "./binaries/polkadot"
chain = "rococo-local"
chain_spec_path = "./plain.json"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 2000
chain_spec_path = "../res/niskala/live/live.json"

[[parachains.collators]]
name = "mandala-collator-1"
command = "./binaries/mandala"

[[parachains.collators]]
name = "mandala-collator-2"
command = "./binaries/mandala"
```

Any pointers?

**Comment by pepoviola** [comment]
Hi @ical10,
                     The _key_ `force_decarator` should be al parachain level, can you try with this:
                     
```toml
[settings]
timeout = 1000


[relaychain]
default_command = "./binaries/polkadot"
chain = "rococo-local"
chain_spec_path = "./plain.json"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 2000
force_decorator = "generic-evm"
chain_spec_path = "../res/niskala/live/live.json"

[[parachains.collators]]
name = "mandala-collator-1"
command = "./binaries/mandala"

[[parachains.collators]]
name = "mandala-collator-2"
command = "./binaries/mandala"
```             

Closing now, please re-open if doesn't works and we can debug it.
Thanks!!
