### ISSUE TITLE
Cannot run network with polkadot-local relaychain

### ISSUE THREAD

**Issue by ntn-x2** [paritytech/zombienet#1867]
### Issue Description

I am trying to use the `polkadot-local` relay spec to set up a ZN network. Nevertheless, the parachain never gets to produce any blocks, and no errors is generated in the logs. I am not sure if this is how `polkadot-local` is supposed (not) to work, or if I am missing some additional configurations.

### Steps to reproduce the issue

Use the following basic network setup config:

```yaml
settings:
    node_verifier: "None"
    provider: "kubernetes"
    timeout: 18000

relaychain:
    chain: polkadot-local
    # Generated from https://github.com/polkadot-fellows/runtimes with `cargo run -p chain-spec-generator -- polkadot-local`
    chain_spec_path: runtimes/spiritnet/polkadot-local-v1.3.2-e220854.json
    default_image: "{{RELAY_IMAGE}}"
    nodes:
        - name: "relay-alice"
          rpc_port: "{{RELAY_RPC}}"
          args:
              - "-lparachain=debug"
        - name: "relay-bob"
        - name: "relay-charlie"

parachains:
    - id: 2086
      chain: spiritnet-dev

      collators:
          - command: "node-executable"
            image: "{{PARA_IMAGE}}"
            name: "para-alice"
            rpc_port: "{{PARA_RPC}}"
          - command: "node-executable"
            image: "{{PARA_IMAGE}}"
            name: "para-bob"
```

the following `.env` file:

```
RELAY_IMAGE=parity/polkadot:v1.15.2
RELAY_RPC=50001
PARA_IMAGE=kiltprotocol/kilt-node:1.14.3
PARA_RPC=50010
```

and the following command:

`env $(cat runtimes/spiritnet/.env | xargs) yarn zombienet --spawn-concurrency=3 spawn runtimes/spiritnet/network.yaml`

### Describe the results you received

The parachain does not produce nor attempts to author any blocks.

### Describe the results you expected

Either an error or actually blocks being produced.

### Zombienet version

1.3.109

### Provider

Kubernetes

### Provider version

```yaml
kubectl version v1.26.1
```

### Upstream Latest Release

Yes

### Additional environment details

See snippets above.

### Additional information

It works if a replace the custom chainspec with `rococo-local`.

**Comment by pepoviola** [comment]
Hi @ntn-x2, thanks for your feedback. Does the custom chain-spec is in `plain` mode? if not we can't customize it to spawn the new network. Also, you can use the [chain-spec-generator](https://github.com/polkadot-fellows/runtimes/tree/main/chain-spec-generator) to get a `plain` version of polkadot local. 
With the plain version should work as expected, please ping me if not and we can touch base and debug.
Thx!

**Comment by ntn-x2** [comment]
Hi. Yes, our chain spec is a preset of our binary, and it's a plain one. I did generate one for polkadot, which I attach here.
[polkadot-1.3.2-plain.json](https://github.com/user-attachments/files/16961082/polkadot-1.3.2-plain.json)

**Comment by ntn-x2** [comment]
This is the chainspec generated by using the `spiritnet-dev` chain preset.

[spiritnet-dev-plain.json](https://github.com/user-attachments/files/16961106/spiritnet-dev-plain.json)

**Comment by pepoviola** [comment]
Hi @ntn-x2, thanks for the info. Did you get any error? Or just the parachain doesn't produce blocks? If this is the case, does the relaychain is compiled with `fast-runtime`? Can you check the session time and if the parachain is onboarded?

Thanks!!

**Comment by ntn-x2** [comment]
@pepoviola I get no error whatsoever on either side. I also noticed parachain collators are not even attempting to author blocks, which is what made me think it could be something related to the nature of the Polkadot runtime. I get the same error with a `kusama-local` relaychain. And I am using the official Docker image from parity, so I don't think that's compiled with `fast-runtime`. As for the chainspec, I generate it from the release branch and specify no additional features, so that should also be ok.

**Comment by ntn-x2** [comment]
Hey. I did not generate the chainspec with the `fast-runtime` feature. Now I did, and I get something about the genesis preset not being found.

Here's the PR: https://github.com/KILTprotocol/kilt-node/pull/714. `cd` into the `zombienet` folder, run `yarn` and then `yarn spawn:spiritnet:with-env`, and you should get to the same point I am at. If you replace the chainspec with the one build without the `fast-runtime` feature, then you get to the point where the chain is not authoring any blocks.

**Comment by ntn-x2** [comment]
I tried it with the pre-release of the paseo relaychain, 1.3.1, and I am in the same situation. Could it be due to the fact that the peregrine-dev chain ID sets the relaychain extension part of the chainspec to `rococo_local`? https://github.com/KILTprotocol/kilt-node/blob/d9552b70160465eaedd7263db450aa70f49667df/nodes/parachain/src/chain_spec/utils.rs#L55. I am under the assumption this would be overridden by Zombienet.

**Comment by ntn-x2** [comment]
Update n. 2:

I have tried with few other configurations, which confirmed that the only relaychain that seems to work, at the moment, is `rococo-local`. 

Here's a network configuration which uses `westend-local` for the relaychain, and `asset-hub-westend-local` for the parachain:

```yaml
settings:
    node_verifier: None
    provider: kubernetes
    timeout: 18000

relaychain:
    chain: westend-local
    default_image: parity/polkadot:v1.15.2
    nodes:
        - name: relay-alice
          rpc_port: 50001
          args:
              - -lparachain=debug
        - name: relay-bob
        - name: relay-charlie
        - name: relay-dave

parachains:
    - id: 2086
      chain: asset-hub-westend-local

      collators:
          - image: parity/polkadot-parachain:1.15.2
            name: para-alice
            rpc_port: 50010
          - image: parity/polkadot-parachain:1.15.2
            name: para-bob
          - image: parity/polkadot-parachain:1.15.2
            name: para-charlie
```

Using the same config, but replacing `westend-local` with `rococo-local` works fine. Hence, the following config works:

```yaml
settings:
    node_verifier: None
    provider: kubernetes
    timeout: 18000

relaychain:
    chain: rococo-local
    default_image: parity/polkadot:v1.15.2
    nodes:
        - name: relay-alice
          rpc_port: 50001
          args:
              - -lparachain=debug
        - name: relay-bob
        - name: relay-charlie
        - name: relay-dave

parachains:
    - id: 2086
      chain: asset-hub-westend-local

      collators:
          - image: parity/polkadot-parachain:1.15.2
            name: para-alice
            rpc_port: 50010
          - image: parity/polkadot-parachain:1.15.2
            name: para-bob
          - image: parity/polkadot-parachain:1.15.2
            name: para-charlie
```
