### ISSUE TITLE
Unrecognized subcommand 'export-genesis-state'

### ISSUE THREAD

**Issue by magecnion** [paritytech/zombienet#1882]
### Issue Description

I'm trying to run the Zombienet environment with a collator using the Frontier runtime.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Build frontier with polkadot-sdk v1.11.0
2. Run zombienet with the following configuration:
```toml
[settings]
timeout = 1000

[relaychain]
default_image = "paritypr/polkadot-debug:master"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

[[parachains]]
id = 100

  [parachains.collator]
  name = "collator01"
  command =  "/frontier/target/release/frontier-template-node"
```

### Describe the results you received

```
error: unrecognized subcommand 'export-genesis-state'

  tip: a similar subcommand exists: 'export-state'

Usage: frontier-template-node [OPTIONS]
       frontier-template-node <COMMAND>

For more information, try '--help'
```

### Describe the results you expected

It should run a network with a collator that includes the frontier runtime.

### Zombienet version

1.3.110

### Provider

Native

### Provider version

```yaml
## For binaries
- polkadot: image from `paritypr/polkadot-debug:master`
- polkadot-parachain: https://github.com/polkadot-evm/frontier/tree/polkadot-v1.11.0
```

### Upstream Latest Release

Yes

**Comment by pepoviola** [comment]
Hi @magecnion, I think the issue is that the needed `subcommand`s are not available in the collator binary.

```rust
	/// Export the genesis state of the parachain.
	#[command(alias = "export-genesis-state")]
	ExportGenesisHead(cumulus_client_cli::ExportGenesisHeadCommand),

	/// Export the genesis wasm of the parachain.
	ExportGenesisWasm(cumulus_client_cli::ExportGenesisWasmCommand),
```

Does this binary works before with zombienet?

**Comment by magecnion** [comment]
I see @pepoviola. It is the first time I am trying to run Frontier binary with Zombienet, but looking at previous versions, it doesn't include those commands either. Do I need to implement those commands, or is there any workaround I can use?

**Comment by pepoviola** [comment]
You can set the `wasm`/`head` of the parachain using this keys (at parachain level)

```toml
genesis_wasm_path = "<path to wasm>"
genesis_state_path = "<path to head/state>"
```

e.g

```
[[parachains]]
id = 100
genesis_wasm_path = "<path to wasm>"
genesis_state_path = "<path to head/state>"

  [parachains.collator]
  name = "collator01"
  command =  "/frontier/target/release/frontier-template-node"
```

Thx!
