### ISSUE TITLE
Dockerizing Zombienet

### ISSUE THREAD

**Issue by dudo50** [paritytech/zombienet#1921]
### Issue Description

Currently, even after exposing endpoints my dockerized version of zombienet doesn't seem to allow to connect into PJS,

<img width="1725" alt="Sn" src="https://github.com/user-attachments/assets/625954c8-943a-41c6-85e7-1ab520b325a8">

Zombienet starts fine
<img width="974" alt="S" src="https://github.com/user-attachments/assets/08ad523c-eda9-4357-80c4-77d1c34b539e">

### Steps to reproduce the issue

Steps to reproduce the issue
1. Running docker build
2. Starting docker
3. Clicking on zombienet endpoint

### Describe the results you received

So when I click on Zombienet endpoint it stays on initiating in PJS and it never connects to zombienet

### Describe the results you expected

How can I ensure, that zombienet endpoints are accessible?

### Zombienet version

Latest

### Provider

Native

### Provider version

```yaml
latest polkadot parachain and polkadot relay chain

Here, I expose ports
EXPOSE 20000-80000

I use this command 
# Launch zombienet
CMD ["./zombienet-linux-x64", "-p", "native", "-c", "1", "spawn", "config-both.toml"]
```

### Upstream Latest Release

Yes

### Additional environment details

Linux docker container:

official rust one

`FROM rust:latest`

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by pepoviola** [comment]
Hi @dudo50, thanks for the feedback. Just to understand and try to reproduce. You are using zombienet `native` provider inside a docker container right? which url are you using for connecting to `pjs`?

Thanks again for the feedback!

**Comment by dudo50** [comment]
Thanks @pepoviola for quick reply, the "Direct link"

eg:
`│ Direct Link                  │ https://polkadot.js.org/apps/?rpc=ws://127.0.0.1:40895#/explorer`

Yes, I use native

**Comment by pepoviola** [comment]
Hi @dudo50, the `Direct link` will not work if you `expose` the ports in the container since is using `127.0.0.1` as ip instead of the ip of the container. You will need to `publish` the ports  to allocate those on your host machine or change the ip to use the one from the container. Is something you see viable in your  use-case?

Thanks!

**Comment by dudo50** [comment]
Can you provide some guidance on how to do this?

It is definitely viable.

Thanks!

**Comment by pepoviola** [comment]
> Thanks @pepoviola - Can you provide some guidance on how to do this?
> 
> It is definitely viable.
> 
> Thanks!

Great, yes. can you pointing here the repo/docker script you are using?
Thanks!

**Comment by dudo50** [comment]
Sure! Here is directly the link to dockerfile:
https://github.com/paraspell-research/xcnft-pallet/blob/main/Dockerfile

Thanks again!

**Comment by pepoviola** [comment]
Hi @dudo50, can you use something like 
```toml
[relaychain]

default_command = "../target/release/polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  rpc_port = 9910

  [[relaychain.nodes]]
  name = "bob"
  rpc_port = 9911

  [[relaychain.nodes]]
  name = "charlie"
  rpc_port = 9912

  [[relaychain.nodes]]
  name = "dave"
  rpc_port = 9913

[[parachains]]
id = 1000

  [parachains.collator]
  name = "parachain-A-1000-collator01"
  command = "../target/release/parachain-template-node"
    args = [
		"-lparachain=debug,xcm::process-message=trace,xcm::execute=trace,xcm::process=trace"
	]
  rpc_port = 9920

[[parachains]]
id = 1001

  [parachains.collator]
  name = "parachain-A-1001-collator01"
  command = "../target/release/parachain-template-node-two"
  args = [
		"-lparachain=debug,xcm::process-message=trace,xcm::execute=trace,xcm::process=trace"
	]
  rpc_port = 9921
  ```
  and the when you run use
  
  ```
  docker run --network=host --platform linux/x86_64 -p 9910-9913:9910-9913 -p 9920-9921:9920-9921 --rm -it polkadot-sdk-image:latest
```
So you publish  the fixed ports for `pjs`

Thanks!
