### ISSUE TITLE
Cant start collator in docker on mac

### ISSUE THREAD

**Issue by bran0h** [paritytech/zombienet#2010]
### Issue Description

Hey I am trying to dockerize my parachain test network with zombienet but i am getting this error:

```log
┌─────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Pod                     │ temp-collator                                                                                      │
├─────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Status                  │ Launching                                                                                          │
├─────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Command                 │ bash -c ../target/release/parachain-template-node export-genesis-head -d /tmp/zombie-              │
│                         │ 99e50cc4a155428b3d9778b4e288b851_-1-CYdABeGhmskN/export-genesis-state/1000 --chain /tmp/zo         │
│                         │ mbie-99e50cc4a155428b3d9778b4e288b851_-1-CYdABeGhmskN/1000-rococo-local.json /tmp/zombie-9         │
│                         │ 9e50cc4a155428b3d9778b4e288b851_-1-CYdABeGhmskN/cfg/genesis-state-1000 && ../target/releas         │
│                         │ e/parachain-template-node export-genesis-wasm --chain /tmp/zombie-99e50cc4a155428b3d9778b4         │
│                         │ e288b851_-1-CYdABeGhmskN/1000-rococo-local.json /tmp/zombie-99e50cc4a155428b3d9778b4e288b8         │
│                         │ 51_-1-CYdABeGhmskN/cfg/genesis-wasm-1000                                                           │
└─────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
Error:           Error: Command failed with exit code 1: bash -c ../target/release/parachain-template-node export-genesis-head -d /tmp/zombie-99e50cc4a155428b3d9778b4e288b851_-1-CYdABeGhmskN/export-genesis-state/1000 --chain /tmp/zombie-99e50cc4a155428b3d9778b4e288b851_-1-CYdABeGhmskN/1000-rococo-local.json /tmp/zombie-99e50cc4a155428b3d9778b4e288b851_-1-CYdABeGhmskN/cfg/genesis-state-1000 && ../target/release/parachain-template-node export-genesis-wasm --chain /tmp/zombie-99e50cc4a155428b3d9778b4e288b851_-1-CYdABeGhmskN/1000-rococo-local.json /tmp/zombie-99e50cc4a155428b3d9778b4e288b851_-1-CYdABeGhmskN/cfg/genesis-wasm-1000
2025-04-03 11:34:42 Cannot create a runtime error=Other("runtime requires function imports which are not present on the host: 'env:_RNvCs6s5TXQrOxQg_7___rustc17rust_begin_unwind'")
Error: Service(Client(VersionInvalid("Other error happened while constructing the runtime: runtime requires function imports which are not present on the host: 'env:_RNvCs6s5TXQrOxQg_7___rustc17rust_begin_unwind'")))

undefined
┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Node'              │ /tmp/zombie-99e50cc4a155428b3d9778b4e288b851_-1-CYdABeGhmskN/logs                                  │
│ s logs:            │                                                                                                    │
│ m                  │                                                                                                    │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘

 Error:          Error: Command failed with exit code 2: bash -c kill -9 
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Here is my config.toml:
```toml
[relaychain]

default_command = "./polkadot"
default_args = ["-lparachain=debug"]

chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
rpc_port = 9910

[[relaychain.nodes]]
name = "bob"
rpc_port = 9911

[[relaychain.nodes]]
name = "charlie"
rpc_port = 9912

[[relaychain.nodes]]
name = "dave"
rpc_port = 9913

[[parachains]]
id = 1000
cumulus_based = true

[parachains.collator]
name = "parachain-A-1000-collator01"
command = "../target/release/parachain-template-node"
args = [
    "-lparachain=debug,xcm::process-message=trace,xcm::execute=trace,xcm::process=trace",
]
rpc_port = 9920

```
2. I am starting the zombienet in Docker like this:
`CMD ["./zombienet-linux-x64", "-p", "native", "-c", "1", "spawn", "config.toml"]`
3. And then starting the docker with this command:
`docker run --platform linux/amd64 -p 9910-9913:9910-9913 -p 9920-9921:9920-9921 --rm -it polkadot-sdk-image:latest`

### Describe the results you received

As I mentioned earlier i am getting the error

### Describe the results you expected

I was trying to run it localy without docker and its working, I have issue only with dockerized version

### Zombienet version

v1.3.127/zombienet-linux-x64

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot-stable2412-4/polkadot

## Docker
Docker version 27.4.0, build bde2b89
```

### Upstream Latest Release

No

### Additional environment details

My machine - Apple Macbook M3 Pro - 18GB
OS - Sonoma 14.6.1 (23G93)
