### ISSUE TITLE
Error: Application(Input("Error parsing spec file: missing field `consensusEngine` at line 146 column 1"))

### ISSUE THREAD

**Issue by bredamatt** [paritytech/zombienet#272]
Thanks for providing zombienet! 

There seems to be an issue in the example, as the chain-spec appears to miss a `consensusEngine` parameter. 

I am using a local `kind` cluster on macOS intel chip with:

- 1 master
- 3 workers

These are my collator logs:

```
k logs collator01 -n zombie-e536db7eb18cc6679e4e1367b2381300
Defaulted container "collator01" out of: collator01, transfer-files-container (init)
+ export PATH=/cfg:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/cfg:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ pipe=/tmp/zombiepipe
+ trap 'rm -f /tmp/zombiepipe' EXIT
+ [[ ! -p /tmp/zombiepipe ]]
+ mkfifo /tmp/zombiepipe
+ child_pid=
+ CMD=($@)
+ child_pid=9
+ ls /proc/9
+ adder-collator --chain /cfg/rococo-local.json --name collator01 --rpc-cors all --unsafe-rpc-external --rpc-methods unsafe --unsafe-ws-external --no-mdns --node-key 5e123980fad4770d9ab5b7df7bbee8499943822a8555d11995e8203210065342 --no-telemetry --parachain-id 100 --bootnodes /ip4/10.244.1.3/tcp/30333/ws/p2p/12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm --listen-addr /ip4/0.0.0.0/tcp/30333/ws --base-path /data
+ read line
Error: Application(Input("Error parsing spec file: missing field `consensusEngine` at line 146 column 1")
```

Here is the `.toml`:

```
[settings]
timeout = 1000

[relaychain]
default_image = "paritypr/polkadot-debug:master"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

[[parachains]]
id = 100

  [parachains.collator]
  name = "collator01"
  image = "paritypr/colander:4131-ccd09bbf"
  command = "adder-collator"
```

**Comment by pepoviola** [comment]
Hi @bredamatt, thanks for use `zombienet` and report this issue. The problem is the `tag` of the `colander` image (is an old one). I updated the `readme` to use the `master` tag. Can you try with this config.

```toml
[settings]
timeout = 1000

[relaychain]
default_image = "paritypr/polkadot-debug:master"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

[[parachains]]
id = 100

  [parachains.collator]
  name = "collator01"
  image = "paritypr/colander:master"
  command = "adder-collator"
```

Closing here, please re-open if doesn't work in your end.

Again, thanks for using zombienet and the feedback!!
