### ISSUE TITLE
API initialization is failed in Parachain

### ISSUE THREAD

**Issue by sirius651** [paritytech/zombienet#278]
Hi, I tried to connect relay-parachain between Kusama and [Shiden](https://github.com/AstarNetwork/Astar/releases/tag/v4.15.0). But it seems the node is not running. here's the config.

```
[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "kusama-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2007
chain = "shiden-dev"

  [[parachains.collator]]
  name = "collator1"
  image = "docker.io/staketechnologies/astar-collator:latest"
  command = "astar-collator"
  args = ["-lparachain=debug”, “--force-authoring”, “--execution=wasm"]
```

and run the script.

I can see the message as 'Network launched'. and when I browse to Node direct link for Kusama-local, it works well.
but when I browse for Parachain-collator (astar), initializing connection is long pending. it seems not running on Parachain properly.

here's the debug log for parachain
```
launching collator pod with image paritypr/colander:4131-e5c7e975
		 with command: /cfg/zombie-wrapper.sh adder-collator --chain /cfg/kusama-local.json --name collator --rpc-cors all --unsafe-rpc-external --rpc-methods unsafe --unsafe-ws-external --no-mdns --node-key 53cf10627db4ce8abcddad56fc510cdfc58bfe587b0cbb6772f1f0727266e565 --no-telemetry --parachain-id 2007 --bootnodes /ip4/10.1.1.46/tcp/30333/ws/p2p/12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm --listen-addr /ip4/0.0.0.0/tcp/30333/ws --base-path /data
```

any miss thing or idea to resolve this?

**Comment by pepoviola** [comment]
Hi @sirius651, the `toml` config for the collator should use single `[]` and also add the `cumulus_based` flag. Can you try with this?

```toml
[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "kusama-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2007
chain = "shiden-dev"
cumulus_based = true

  [parachains.collator]
  name = "collator1"
  image = "docker.io/staketechnologies/astar-collator:latest"
  command = "astar-collator"
  args = ["-lparachain=debug”, “--force-authoring”, “--execution=wasm"]
  ```
  
  Let me know if doesn't works.
  Thanks!
