### ISSUE TITLE
[bug] Use collator command from collator_groups if no collator is defined

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#289]
reproduce

```toml
  [settings]
  timeout = 1000

  [relaychain]
  default_image = "docker.io/paritypr/synth-wave:4131-0.9.12-ccd09bbf-29a1ac18"
  chain = "rococo-local"
  command = "polkadot"

    [[relaychain.nodes]]
    name = "alice"
    validator = true
    extra_args = [ "-lparachain=debug" ]

    [[relaychain.nodes]]
    name = "bob"
    validator = true
    extra_args = [ "-lparachain=debug" ]
    add_to_bootnodes = true


  [[parachains]]
  id = 100
  cumulus_based = true

    [[parachains.collator_groups]]
      count = 2
      [parachains.collator_groups.collator]
      name = "collator"
      command = "polkadot-parachain"
      args = ["-lparachain=debug"]

  [types.Header]
  number = "u64"
  parent_hash = "Hash"
  post_state = "Hash"
 ```
 
 Zombienet will use the `default` collator command (`adder-collator`) since no collator is defined.

Thanks @wirednkod for found it!
