### ISSUE TITLE
Adding a link checker to the CI

### ISSUE THREAD

**Issue by crystalin** [paritytech/zombienet#398]
Some links in the readme are not working anymore. It would be great to have a link checked in the CI for merging PR.
Ex:
```
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
```
