### ISSUE TITLE
Test multiple images of the same chain/para

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#457]
Following the request of this PR for [backward compatibility testing](https://github.com/paritytech/polkadot/issues/6001), it would make sense to have a way to generically test different branches in parallel, with firing up 2 different images and being able to pass the secondary_image into one of the relay chain nodes as can be seen below:

add env vars:
```bash
export ZOMBIENET_POLKADOT_IMAGE_MASTER=docker.io/paritypr/polkadot-debug:master
export ZOMBIENET_POLKADOT_IMAGE_BRANCH=docker.io/paritypr/polkadot-debug:branchX
```
and in the configuration of Zombienet:
```toml
[relaychain]
default_image = "{{ZOMBIENET_POLKADOT_IMAGE_MASTER}}"
secondary_image = "{{ZOMBIENET_POLKADOT_IMAGE_BRANCH}}" 
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "charlie"
  image = "{{secondary_image}}"

  [[relaychain.nodes]]
  name = "bob"
```

cc @pepoviola

**Comment by wirednkod** [comment]
Apparently this already exists by setting the image to use at node level and that will override the `default_image`:
e.g
```toml
[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE_SECONDARY}}"
  [[relaychain.nodes]]
  name = "bob"
```

Closing this issue
