### ISSUE TITLE
Error pulling image for pod

### ISSUE THREAD

**Issue by sacha-l** [paritytech/zombienet#584]
I'm trying to launch a zombienet using Docker on macOS but get the following error:

```bash
Error: Error pulling image for pod : temp
    at KubeClient.<anonymous> (/snapshot/javascript/packages/orchestrator/dist/providers/k8s/kubeClient.js)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/javascript/packages/orchestrator/dist/providers/k8s/kubeClient.js)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Here's the toml file:

```toml
[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000

  [parachains.collator]
  name = "collator01"
  image = "/bin/parachain-v0.9.30-1000"
  command = "adder-collator"
```

It's not clear what's causing this error and how to fix it. Any pointers appreciated.
