### ISSUE TITLE
Setting RUST_LOG for collators

### ISSUE THREAD

**Issue by bkontur** [paritytech/zombienet#616]
please, how  can I set RUST_LOG for collators?

this does not work for me:

```
[[parachains]]
id = 1013
chain = "bridge-hub-rococo-local"
cumulus_based = true
default_args = [ "-lparachain=debug,runtime=debug,xcm::weight=trace,xcm::filter_asset_location=trace,xcm::send_xcm=trace,xcm::barriers=trace,xcm::barrier=trace,xcm::execute_xcm=trace,xcm::contains=trace,xcm::execute_xcm_in_credit,xcm::process_instruction=trace,xcm::currency_adapter=trace,xcm::origin_conversion=trace,xcm::fungibles_adapter=trace,xcm::process=trace,xcm::execute=trace" ]
```

**Comment by pepoviola** [comment]
Hi @bkontur, `parachains` don't have `default_args` you can set the `args` to each collator like this
```toml
[[parachains]]
id = 1013
chain = "bridge-hub-rococo-local"
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "<image>"
  command = "<cmd>"
  args = [ "-lparachain=debug,runtime=debug,xcm::weight=trace,xcm::filter_asset_location=trace,xcm::send_xcm=trace,xcm::barriers=trace,xcm::barrier=trace,xcm::execute_xcm=trace,xcm::contains=trace,xcm::execute_xcm_in_credit,xcm::process_instruction=trace,xcm::currency_adapter=trace,xcm::origin_conversion=trace,xcm::fungibles_adapter=trace,xcm::process=trace,xcm::execute=trace" ]
```

You can also check to the network topology file spec [here](https://paritytech.github.io/zombienet/network-definition-spec.html).

Thanks!!
