### ISSUE TITLE
[bug] allow `toml` comments in file `first char`

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#705]
This valid `toml` produce an error in `zombienet` because of the first line comment.

```toml
# examples/0002-small-network-paras.toml
[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"
chain = "rococo-local"

  [[relaychain.node_groups]]
  name = "validator"
  count = 5

[[parachains]]
id = 1000
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-parachain:latest"
  command = "polkadot-parachain"

[[parachains]]
id = 1001
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-parachain:latest"
  command = "polkadot-parachain"
```

https://github.com/paritytech/zombienet/blob/main/javascript/packages/utils/src/fs.ts#L125

```ts
fileType?.toLocaleLowerCase() === "toml" &&
    tomlChar.test(firstChar)
```
should handle comments.
