### ISSUE TITLE
Add zombienet releases for mac `arm64`

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#710]
We should update the CI to build on this arch.

**Comment by pepoviola** [comment]
GH actions don't support macos arm64 runners at the moment. This pr cover the changes to apply when they add support.
https://github.com/paritytech/zombienet/pull/714

**Comment by pepoviola** [comment]
Re-open here, since in this case is the release of `zombienet` itself not from polkadot.

**Comment by jmg-duarte** [comment]
Adding a matrix here should work
https://github.com/paritytech/zombienet/blob/875a273502d81c29985eff3f78521650f26c2c28/.github/workflows/release.yaml#L74-L75

Something like this:
```yaml
build_release_for_mac:
    name: build_release_for_mac
    needs: build_release_for_linux
    matrix: 
        target: [ { runner: macos-13, arch: x86_64 }, { runner: macos-14, arch: arm64 } ]
    runs-on: ${{ matrix.target.runner }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # redacted for brevity

      - name: upload macos artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.build_release_for_linux.outputs.upload_url }}
          asset_path: ./javascript/bins/zombienet-macos
          asset_name: zombienet-macos-${{ matrix.target.arch }}
          asset_content_type: application/octet-stream
```

I can open the PR if you think this is ok
