### ISSUE TITLE
tricks to speed up extrinsic processing

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/zombienet#721]
I'm working with a very basic Zombienet config for Rococo Contracts

```toml
[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = ["-lparachain=debug"]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1000
cumulus_based = true
chain = "contracts-rococo-local"

[parachains.collator]
name = "collator"
image = "docker.io/parity/polkadot-parachain:latest"
command = "polkadot-parachain"
args = ["-lparachain=debug"]
```

When submitting a `instantiateWithCode` extrinsic to `alice`, the transaction status hangs on `ready`. Aka., the submitted extrinsic is valid. Unfortunately, it take many minutes (or sometimes so long that I'm unsure of whether it would in fact eventually be processed).

Any tips on speeding up the network's block times or on determining possible source of slowness?
