### ISSUE TITLE
[bug] handle correct the `max_nominations` related to the `validators` set.

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#733]
This config with 10 validators will try to create nominators with a max nominations of `24` (our default) and will break the chain-spec (with nulls). We should handle and set the `max_nominations` related to the validators set.

```toml
[settings]
timeout = 4800
bootnode = true

[relaychain.genesis.runtime.configuration.config]
  max_validators_per_core = 1
  needed_approvals = 21

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "kusama-local"
chain_spec_command = "polkadot build-spec --chain kusama-local --disable-default-bootnode"
default_command = "polkadot"
random_nominators_count = 250

[relaychain.default_resources]
limits = { memory = "8G", cpu = "4" }
requests = { memory = "2G", cpu = "1" }

  [[relaychain.node_groups]]
  name = "honest-validator"
  count = 8
  args = ["-lparachain=debug,runtime=debug"]

  [[relaychain.node_groups]]
  image = "{{MALUS_IMAGE}}"
  name = "malus-validator"
  command = "malus dispute-ancestor"
  args = ["--fake-validation=approval-invalid", "-lparachain=debug,MALUS=trace"]
  count = 2

{% for id in range(2000,2019) %}
[[parachains]]
id = {{id}}
addToGenesis = true
genesis_state_generator = "undying-collator export-genesis-state --pov-size={{10000*(id-1999)}} --pvf-complexity={{id - 1999}}"
    [parachains.collator]
    image = "{{COL_IMAGE}}"
    name = "collator"
    command = "undying-collator"
    args = ["-lparachain=debug", "--pov-size={{10000*(id-1999)}}", "--parachain-id={{id}}", "--pvf-complexity={{id - 1999}}"]
{% endfor %}

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
```

cc @tdimitrov
