### ISSUE TITLE
Error when using `-d` option

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#769]
When `-d` option is used with CLI the following error occurs:
```bash
 Error:  	 Error: Cannot find module './firstnet/polkadot-local-plain.json'
Require stack:
- /snapshot/javascript/packages/orchestrator/dist/orchestrator.js
- /snapshot/javascript/packages/orchestrator/dist/index.js
- /snapshot/javascript/packages/cli/dist/cli.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
```

The `toml` file that used is of a simple network:
```toml
[settings]
provider = "native"
timeout = 1000

[relaychain]
chain = "polkadot-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"
```

![image](https://user-images.githubusercontent.com/5408605/222773613-18959f5a-e6f3-4569-933b-04706eeee840.png)
