### ISSUE TITLE
Specify that 1.3.39 fixes an image error 

### ISSUE THREAD

**Issue by JuaniRios** [paritytech/zombienet#794]
When using 1.3.38, and trying to spawn a native network of a parachain and a relay chain:
```sh
 ~/Downloads/zombienet-linux-x64 spawn -p native scripts/zombienet/native/base-rococo-local.toml
```
 I get:
` Error:          Error: Image's URL is invalid:  parity/polkadot-parachain:latest`

Using 1.3.39 solves the error.

.toml:
```toml
[relaychain]
default_command = "polkadot"
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"
	validator = true

	[[relaychain.nodes]]
	name = "bob"
	validator = true

[[parachains]]
id = 2000
cumulus_based = true
	[[parachains.collators]]
	name = "collator1"
	command = "./target/release/polimec-parachain-node"
	validotor = true
	args = ["-lparachain=debug"]
```
